session.menuFile: /tmp/fluxbox-home/.fluxbox/menu
session.screen0.rootCommand: xsetroot -solid #111113
session.screen0.toolbar.visible: true
session.screen0.toolbar.height: 28
session.screen0.toolbar.placement: BottomCenter
session.screen0.toolbar.widthPercent: 100
session.screen0.workspaces: 1
session.screen0.fullMaximization: true
session.screen0.window.focus.alpha: 255
session.overlay.menuDelay: 0
