import pathlib

p = pathlib.Path("packages/db/src/coding-migration.test.ts")
s = p.read_text()

# 1. module-level gate helper (pre-fix lookahead; tokens added in the fix step)
old = """describe("coding migrations are additive (V14, T1)", () => {"""
new = """/**
 * The ONLY non-CREATE statement form an additive coding migration may take:
 * a nullable column add on a coding table. Everything that changes existing
 * rows or column semantics is forbidden — including DEFAULT, COLLATE,
 * GENERATED, and IDENTITY (tightened in fix round r2, MED-2: the r1 comment
 * claimed "no default" but the negative lookahead omitted DEFAULT and
 * siblings; the probe tests below pin them to the actual gate).
 */
function isAdditiveCodingColumnAdd(statement: string): boolean {
  const alterMatch =
    /^ALTER TABLE "([A-Za-z_][A-Za-z0-9_]*)" ADD COLUMN "([A-Za-z][A-Za-z0-9_]*)"/.exec(
      statement,
    );
  return (
    alterMatch !== null &&
    NEW_TABLES.has(alterMatch[1]!) &&
    !/\\b(DROP|RENAME|TRUNCATE|UPDATE|DELETE|INSERT|ALTER COLUMN|CONSTRAINT|REFERENCES|NOT NULL|SET|USING)\\b/i.test(
      statement,
    )
  );
}

describe("coding migrations are additive (V14, T1)", () => {"""
assert s.count(old) == 1, "describe anchor"
s = s.replace(old, new)

# 2. existing gate uses the helper (logic unchanged pre-fix)
old = """        const isCreate = /^CREATE (TABLE|UNIQUE INDEX|INDEX)\\b/.test(statement);
        // S3 (T18) adds one nullable checkpoint column on a coding table via
        // ALTER TABLE — the only non-CREATE form an additive coding migration
        // may take: no default, no constraint, no rewrite of existing rows.
        const alterMatch =
          /^ALTER TABLE "([A-Za-z_][A-Za-z0-9_]*)" ADD COLUMN "([A-Za-z][A-Za-z0-9_]*)"/.exec(
            statement,
          );
        const isAdditiveColumnAdd =
          alterMatch !== null &&
          NEW_TABLES.has(alterMatch[1]!) &&
          !/\\b(DROP|RENAME|TRUNCATE|UPDATE|DELETE|INSERT|ALTER COLUMN|CONSTRAINT|REFERENCES|NOT NULL|SET|USING)\\b/i.test(
            statement,
          );
        expect(isCreate || isAdditiveColumnAdd).toBe(true);"""
new = """        const isCreate = /^CREATE (TABLE|UNIQUE INDEX|INDEX)\\b/.test(statement);
        // S3 (T18) adds one nullable checkpoint column on a coding table via
        // ALTER TABLE — the only non-CREATE form an additive coding migration
        // may take: no default, no constraint, no rewrite of existing rows
        // (gate helper: isAdditiveCodingColumnAdd).
        expect(isCreate || isAdditiveCodingColumnAdd(statement)).toBe(true);"""
assert s.count(old) == 1, "gate anchor"
s = s.replace(old, new)

# 3. probe tests (RED pre-fix: the four variants currently PASS the gate)
old = """  it("the generated prisma client includes the new models", () => {"""
new = """  it("probe (fix r2 MED-2): a DEFAULT-bearing column add FAILS the gate — r1 claimed 'no default' but the lookahead omitted it", () => {
    expect(
      isAdditiveCodingColumnAdd(
        'ALTER TABLE "coding_sessions" ADD COLUMN "x" JSONB DEFAULT \\'{}\\'::jsonb',
      ),
    ).toBe(false);
  });

  it("probe (fix r2 MED-2): a COLLATE-bearing column add FAILS the gate", () => {
    expect(
      isAdditiveCodingColumnAdd('ALTER TABLE "coding_sessions" ADD COLUMN "x" TEXT COLLATE "C"'),
    ).toBe(false);
  });

  it("probe (fix r2 MED-2): a GENERATED column add FAILS the gate", () => {
    expect(
      isAdditiveCodingColumnAdd(
        'ALTER TABLE "coding_sessions" ADD COLUMN "x" TEXT GENERATED ALWAYS AS (upper("y")) STORED',
      ),
    ).toBe(false);
  });

  it("probe (fix r2 MED-2): an IDENTITY column add FAILS the gate", () => {
    expect(
      isAdditiveCodingColumnAdd(
        'ALTER TABLE "coding_sessions" ADD COLUMN "x" BIGINT GENERATED BY DEFAULT AS IDENTITY',
      ),
    ).toBe(false);
  });

  it("probe control: the plain nullable column add still PASSES the gate", () => {
    expect(
      isAdditiveCodingColumnAdd(
        'ALTER TABLE "coding_sessions" ADD COLUMN "secretsAuditHead" JSONB',
      ),
    ).toBe(true);
  });

  it("the generated prisma client includes the new models", () => {"""
assert s.count(old) == 1, "probe anchor"
s = s.replace(old, new)

p.write_text(s)
print("med2 red probes added")
